### ISSUE TITLE
How to generate features for 'Chair' scenario? 19-dimension I guess?

### ISSUE THREAD

**Issue by Xinqi-L** [orangeduck/Motion-Matching#14]
Thanks for your wonderful work!

Features are designed differently in each scenario according to the 'Learned Motion Matching' paper. Could you please kindly share your ideas on **how to design features for 'Chair' scenario**? 

Features for 'Chair' are supposed to be 19-dimension rather than the 27-dimension feature for locomotion as described in the paper.

Thanks!

**Comment by orangeduck** [comment]
Sure, here are the features we use:

Relative 2D position of the chair local to the character (2 dims).
Relative 2D facing direction of the chair local to the character (2 dims).
Left foot position (3 dims)
Right foot position (3 dims)
Left foot velocity (3 dims)
Right foot velocity (3 dims) 
Hip bone velocity (3 dims)

**Comment by Xinqi-L** [comment]
Thanks! I'll try!

I also wonder how to switch from one scenario to another one. For example, there might be a problem when switching from "locomotion" scenario to "chair" scenario as query feature may change from 27-dim to 19-dim. It may not work to simply set current feature as input for new stepper/projector. 
Maybe a compressor will help?

Many thanks!

**Comment by orangeduck** [comment]
The easiest way is to have multiple databases and matching set-ups per scenario. You can still make some components shared such as using the inertialization to switch between scenarios seamlessly.

Another option is to include all features in the database and have dynamic weights which change which ones are actively used in the matching during runtime. However, this is not always easy since some features don't make sense in some contexts (e.g. what is the relative chair position during locomotion?) and this also has worse performance and memory usage.

**Comment by Xinqi-L** [comment]
Got it
Thanks again!!!
