### ISSUE TITLE
Question: the ‘trajectory_rotations_predict’ function

### ISSUE THREAD

**Issue by hui211314dd** [orangeduck/Motion-Matching#15]
![image](https://user-images.githubusercontent.com/8109901/184828548-95976228-9509-4abe-8958-6c3f1db3b27c.png)

Why not code like below ? I guess this would be more accurate😁

![image](https://user-images.githubusercontent.com/8109901/184828384-17c7f50a-72bd-4dd9-8c3a-b23456bede1c.png)

Thanks Daniel!🤞

**Comment by orangeduck** [comment]
In this case, both versions will produce the same result because the spring equations will produce an accurate answer no matter how large the `dt` is (see: https://theorangeduck.com/page/spring-roll-call).

I would expect the compiler to produce slightly faster code for the first version since it does not contain a dependency between iterations of the loop (one iteration does not depend on the previous iteration being completed). This means the compiler can more effectively unroll and auto-vectorize.

Hope that helps!

**Comment by hui211314dd** [comment]
Thanks Daniel
