### ISSUE TITLE
Positions relative to the sim bone

### ISSUE THREAD

**Issue by JackGodfrey122** [orangeduck/Motion-Matching#19]
Hi Daniel. First of all, I really appreciate the fact you open all of this research to the public. Its really refreshing to see. On to the technical stuff...
In the `compute_bone_position_feature` in` database.h`, to get the position of a joint relative to the sim bone, you first calculate the global positions using fk. After that, you then rotate the diff between these two points by the global (global and local are the same in this case I assume as we're concerned with the sim bone) inverse rotation of the sim bone. Why is this? I thought it would have been sufficient to just use that diff? Am I misunderstanding the inputs and outputs of this method?
For reference the code is here:
```cpp
// Compute a feature for the position of a bone relative to the simulation/root bone
void compute_bone_position_feature(database& db, int& offset, int bone, float weight = 1.0f)
{
    for (int i = 0; i < db.nframes(); i++)
    {
        vec3 bone_position;
        quat bone_rotation;
        
        forward_kinematics(
            bone_position,
            bone_rotation,
            db.bone_positions(i),
            db.bone_rotations(i),
            db.bone_parents,
            bone);
        
        bone_position = quat_mul_vec3(quat_inv(db.bone_rotations(i, 0)), bone_position - db.bone_positions(i, 0));
        
        db.features(i, offset + 0) = bone_position.x;
        db.features(i, offset + 1) = bone_position.y;
        db.features(i, offset + 2) = bone_position.z;
    }
    
    normalize_feature(db.features, db.features_offset, db.features_scale, offset, 3, weight);
    
    offset += 3;
}
```
Again, thank you for all your research!

**Comment by orangeduck** [comment]
Hi Jack,

Another way to think about it is like this: the first subtraction `bone_position - db.bone_positions(i, 0)` is like translating the character so that every frame of the animation they are positioned at the origin. However they can still be facing in any direction. The multiplication by the inverse of the sim rotation will then rotate the character so that for every frame in the animation they are always facing in the same forward direction.

This is a much better space to compare bone positions since it is invariant to the overall facing direction of the character in the animation data - i.e. as long as they are in a similar overall pose the position will be similar.

Hope that helps,

Dan

**Comment by JackGodfrey122** [comment]
Hey Dan. That makes perfect sense, thank you! Again, thanks for all your work, I really appreciate it.
